
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Setup Bazel
        uses: abhinavsingh/setup-bazel@v3
      - name: Run all tests
        run: bazel test --config=_gcc --collect_code_coverage  :all
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v1
        with:
          token: ${{a45029ea-3da5-4312-9529-14e2a2e89529}} # not required for public repos
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)

