
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Setup Bazel
        uses: abhinavsingh/setup-bazel@v3
      - name: Run all tests
<<<<<<< HEAD
        run: bazel test --config=_gcc --collect_code_coverage :all
      - name: After success
        run: bash <(curl -s https://codecov.io/bash)

=======
        run: bazel test --config=_gcc :all
>>>>>>> parent of 45c12aa... coverage in CI?
