name: Lint

on: [pull_request]
jobs:
  Linter:
    name: clang-tidy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: C/C++ code linter (clang-tidy, clang-format, and cppcheck)
        uses: ArtificialAmateur/cpp-linter-action@0.01
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    
