name: Lint

on: [pull_request]
jobs:
  Linter:
    name: clang-tidy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run clang-tidy
        uses: HorstBaerbel/action-clang-tidy@1.0
        with:
          scandir: '.'
          builddir: 'build'
          excludedirs: ''
          extensions: 'c,h,C,H,cpp,hpp,cc,hh,c++,h++,cxx,hxx'
          cmakeoptions: ''

    
